version: '3.5'

services:
  postgres:
    image: postgres:11.5-alpine
    env_file: .env
    volumes:
      - ./db-data:/var/lib/postgresql/data
      - ./db:/var/run/postgresql
    expose:
      - 5432
    ports:
      - 5432:5432

  beesmart:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:3000
    command: /bin/bash -c "rails s -p 3000 -b 0.0.0.0"
    env_file: .env
    environment:
      - RAILS_ENV=production
    volumes:
      - ./:/beesmart
    depends_on:
      - postgres
